# common params
depth_registration: false
enable_d2c_viewer: false
enable_point_cloud: false
enable_colored_point_cloud: false
enable_ldp: false
device_preset: "Default"


# enable_laser: true
interleave_ae_mode: "laser"
interleave_frame_enable: true
interleave_skip_enable: false
interleave_skip_index: 1
time_domain: "global" # global, device, system
enable_sync_host_time: true

trigger_out_enabled: true
frames_per_trigger: 0
software_trigger_period: 0


# color params
enable_color: false
color_width: 640
color_height: 480
color_fps: 30
color_format: "MJPG"
enable_color_auto_exposure: false
color_exposure: 50 # 5ms
color_gain: 16 # -1 default


#left ir params
enable_left_ir: true
left_ir_width: 640
left_ir_height: 480
left_ir_fps: 30
left_ir_format: "Y8"
enable_ir_auto_exposure: true
ir_exposure: 5000 # 5ms
ir_gain: 16 # -1 default

# depth params
enable_depth: true
depth_width: 640
depth_height: 480
depth_fps: 30
depth_format: "Y16"
