# config/*.yaml files are used to configure the camera parameters
---
orbbec_ros:
    multi_camera_parameters:

        launch_device_camera1:
            config_file_path: "multicamera_test/gemini330_series_test1.yaml"
            # default period 0.0; unit: second
            period: 0.0
            camera_name: "camera1"
            usb_port: "2-2-4"
            device_num: "2"
            sync_mode: "standalone"

        launch_device_camera2:
            config_file_path: "multicamera_test/gemini330_series_test2.yaml"
            # default period 0.0; unit: second
            period: 2.0
            camera_name: "camera2"
            usb_port: "2-1-2"
            device_num: "2"
            sync_mode: "standalone"
